"""empty message

Revision ID: 3a7b0f4dcb00
Revises: 60713029ded0
Create Date: 2020-08-17 22:13:26.354407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7b0f4dcb00'
down_revision = '60713029ded0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actor', sa.Column('t', sa.String(), nullable=True))
    op.alter_column('Movie', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Movie', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('Actor', 't')
    # ### end Alembic commands ###
