"""empty message

Revision ID: 5335c3fb37c0
Revises: 3a7b0f4dcb00
Create Date: 2020-08-17 22:14:34.063694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5335c3fb37c0'
down_revision = '3a7b0f4dcb00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Actor', 't')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actor', sa.Column('t', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
